// <auto-generated />
using System;
using Api.ClinicaMedica.AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.ClinicaMedica.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250219001309_Primera migracion adaptacion")]
    partial class Primeramigracionadaptacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Especialidades", b =>
                {
                    b.Property<string>("IdEspecialidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEspecialidad");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Medicos", b =>
                {
                    b.Property<string>("IdMedico")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdEspecialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Sueldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMedico");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Pacientes", b =>
                {
                    b.Property<string>("IdPaciente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("ObraSocial")
                        .HasColumnType("bit");

                    b.HasKey("IdPaciente");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Personas", b =>
                {
                    b.Property<string>("IdPersona")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("IdPersona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Medicos", b =>
                {
                    b.HasOne("Api.ClinicaMedica.Entities.Especialidades", "Especialidad")
                        .WithMany("Medicos")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api.ClinicaMedica.Entities.Personas", "Persona")
                        .WithOne("Medico")
                        .HasForeignKey("Api.ClinicaMedica.Entities.Medicos", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Pacientes", b =>
                {
                    b.HasOne("Api.ClinicaMedica.Entities.Personas", "Persona")
                        .WithOne("Paciente")
                        .HasForeignKey("Api.ClinicaMedica.Entities.Pacientes", "IdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Especialidades", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("Api.ClinicaMedica.Entities.Personas", b =>
                {
                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
